#!/bin/bash

##################################
#
# DOT FILES INSTALLER
#
##################################

# Vim
cp -a ./.vim ~/

# Git
cp ./git/.gitignore_global ~/ && \
  git config --global core.excludesfile '~/.gitignore_global'

# tmux
cp -a ./tmux/.tmux.conf ~/.tmux.conf

# Oh My Zsh
cp ./zsh/.my-zsh-custom-settings ~/ && \
  grep -q -F 'source ~/.my-zsh-custom-settings' ~/.zshrc || echo "source ~/.my-zsh-custom-settings" >> ~/.zshrc

