#!/bin/bash

##################################
#
# DOT FILES INSTALLER
#
##################################

# Vim
rm -rf ~/.vim && \
  cp -a ./.vim ~/

# Git
cp -a ./git/.git* ~/

# tmux
cp -a ./tmux/.tmux.conf ~/.tmux.conf

# tmate
cp -a ./tmate/.tmate.conf ~/.tmate.conf

# Shell extras
# Install only if OS == LINUX
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  FILE=~/.zshrc
  if [ -f "$FILE" ]; then
    # Zsh
    [[ -f ~/.my-zsh-custom-settings ]] && rm ~/.my-zsh-custom-settings
    cp ./sh/.my-zsh-custom-settings ~/ && \
      grep -qF 'source ~/.my-zsh-custom-settings' ~/.zshrc || printf "\n# $USER custom shell:\nsource ~/.my-zsh-custom-settings" >> ~/.zshrc
  fi
  FILE=~/.bashrc
  if [ -f "$FILE" ]; then
    # Bash
    [[ -f ~/.my-bash-custom-settings ]] && rm ~/.my-bash-custom-settings
    cp sh/.my-bash-custom-settings ~/ && \
      grep -qF 'source ~/.my-bash-custom-settings' ~/.bashrc || printf "\n# $USER custom shell:\nsource ~/.my-bash-custom-settings" >> ~/.bashrc
  fi
fi

# Binaries
rm -rf ~/.my-binaries && \
  cp -a ./bins ~/.my-binaries

