#!/bin/bash

##################################
#
# DOT FILES INSTALLER
#
##################################

# Vim
rm -rf ~/.vim && \
  cp -a ./.vim ~/

# Git
cp -a ./git/.git* ~/

# tmux
cp -a ./tmux/.tmux.conf ~/.tmux.conf

# tmate
cp -a ./tmate/.tmate.conf ~/.tmate.conf

# Shell extras
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  cp ./sh/.linux-gnu-custom-settings ~/ && \
    grep -qF 'source ~/.linux-gnu-custom-settings' ~/.zshrc || printf "\n# $USER custom shell:\nsource ~/.linux-gnu-custom-settings" >> ~/.zshrc
elif [[ "$OSTYPE" == "darwin"* ]]; then
  cp ./sh/.darwin-custom-settings ~/ && \
    grep -qF 'source ~/.darwin-custom-settings' ~/.zshrc || printf "\n# $USER custom shell:\nsource ~/.darwin-custom-settings" >> ~/.zshrc
fi

# Binaries
rm -rf ~/.my-binaries && \
  cp -a ./bins ~/.my-binaries

