#!/bin/bash
##################################
#
# GOOGLE VIM HELPER
#
# Used with vim keywordprg.
#
##################################

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  google-chrome-stable https://www.google.com/search?q="$1"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  open -a "Google Chrome" https://www.google.com/search?q="$1"
fi
