#!/bin/bash
##################################
#
# GOOGLE VIM HELPER
#
# Just a shortcut to call Chrome
# from terminal to open a file.
#
##################################

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  google-chrome-stable "$1"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  open -a "Google Chrome" "$1"
fi
